export const products = [
        {
          "availableSizes": ["X", "L", "XL", "XXL"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "14/15 s/nº",
          "id": 0,
          "installments": 9,
          "isFreeShipping": true,
          "price": 10.90,
          "sku": 8552515751438644,
          "style": "White T-shirt",
          "title": "Cropped Stay Groovy off white",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["X", "ML", "L"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "",
          "id": 11,
          "installments": 3,
          "isFreeShipping": true,
          "price": 13.25,
          "sku": 39876704341265610,
          "style": "Wine",
          "title": "Basic Cactus White T-shirt",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/1566412/pexels-photo-1566412.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["XL"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "14/15 s/nº - Jogador",
          "id": 4,
          "installments": 12,
          "isFreeShipping": false,
          "price": 25.9,
          "sku": 9197907543445676,
          "style": "Tony Hawk",
          "title": "Skater Black Sweatshirt",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/1561011/pexels-photo-1561011.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["M", "ML"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "",
          "id": 13,
          "installments": 5,
          "isFreeShipping": true,
          "price": 29.45,
          "sku": 51498472915966370,
          "style": "Tule",
          "title": "Black Tule Oversized",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/1227699/pexels-photo-1227699.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["S", "XS"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "4 MSL",
          "id": 12,
          "installments": 9,
          "isFreeShipping": true,
          "price": 10.9,
          "sku": 12064273040195392,
          "style": "Really Cool T-shirt",
          "title": "Black Batman T-shirt",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/2451200/pexels-photo-2451200.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["X", "L", "XL"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "GPX Poly 1",
          "id": 14,
          "installments": 3,
          "isFreeShipping": true,
          "price": 30.36,
          "sku": 10686354557628304,
          "style": "Mark Zuck have 365 of this one",
          "title": "Blue T-Shirt",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/2896426/pexels-photo-2896426.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["X", "L", "XL", "XXL"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "Treino 2014",
          "id": 15,
          "installments": 5,
          "isFreeShipping": true,
          "price": 17.20,
          "sku": 11033926921508488,
          "style": "",
          "title": "Loose Black T-shirt",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/7643772/pexels-photo-7643772.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["X", "L", "XL", "XXL"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "14/15 s/nº",
          "id": 1,
          "installments": 9,
          "isFreeShipping": true,
          "price": 10.9,
          "sku": 18644119330491310,
          "style": "White T-shirt",
          "title": "Ringer Hall Pass",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/6941486/pexels-photo-6941486.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["X", "L"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "14/15 s/nº",
          "id": 2,
          "installments": 7,
          "isFreeShipping": true,
          "price": 20.9,
          "sku": 11854078013954528,
          "style": "You will like this one",
          "title": "Grey T-shirt",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/5214139/pexels-photo-5214139.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["X", "L"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "2014 s/nº",
          "id": 3,
          "installments": 7,
          "isFreeShipping": true,
          "price": 14.7,
          "sku": 876661122392077,
          "style": "Adidas originals",
          "title": "Black T-shirt with white stripes",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/1027130/pexels-photo-1027130.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
          "availableSizes": ["L", "XL"],
          "currencyFormat": "$",
          "currencyId": "USD",
          "description": "",
          "id": 10,
          "installments": 9,
          "isFreeShipping": true,
          "price": 49.30,
          "sku": 27250082398145996,
          "style": "",
          "title": "Marine Blue T-shirt",
          "quantity" : 1,
          "image" : "https://images.pexels.com/photos/1102777/pexels-photo-1102777.jpeg?auto=compress&cs=tinysrgb&w=600"
        },
        {
            "availableSizes": ["L", "XL"],
            "currencyFormat": "$",
            "currencyId": "USD",
            "description": "",
            "id": 10,
            "installments": 9,
            "isFreeShipping": true,
            "price": 30.60,
            "sku": 27250082398145996,
            "style": "",
            "title": "Marine Black Joggers",
            "quantity" : 1,
            "image" : "https://images.pexels.com/photos/1407354/pexels-photo-1407354.jpeg?auto=compress&cs=tinysrgb&w=600"
          },
          
]
  